# Generated by Django 6.0.7 on 2026-07-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='dec',
        ),
    ]
